site_name: Datascene – Référentiel des métadonnées descriptives du spectacle
theme:
  name: material
  language: fr
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
  custom_dir: overrides
  logo: assets/Datascene_White.svg
  favicon: assets/Datascene_White_carre.svg
markdown_extensions:
  - toc:
      permalink: true
      title: Sur cette page
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: Copyright &copy; 2024 Datascence – Référentiel des métadonnées descriptives du spectacle
plugins:
    - search
    - macros
nav:
  - À propos:
    - Bienvenue: 'index.md'
    - Contribuer: 'contribuer.md'
    - Crédits: 'credits.md'
  - Avant de commencer:
    - Objectifs: 'avant_de_commencer/objectifs.md'
    - Composantes: 'avant_de_commencer/composantes.md'
    - Lignes directrices: 'avant_de_commencer/lignes_directrices.md'
    - Glossaire: 'references/glossaire.md'
  - Modèle de données:
    - 'modele/index.md'
    - Classes principales:
      - modele/classes_principales/index.md
      - Spectacle: 'references/proprietes/spectacle.md'
      - Représentation: 'references/proprietes/representation.md'
      - Série: 'references/proprietes/serie.md'
      - Lieu: 'references/proprietes/lieu.md'
      - Salle: 'references/proprietes/salle.md'
      - Contributeur: 'references/proprietes/contributeur.md'
      - Oeuvre: 'references/proprietes/oeuvre.md'
    - Classes utilitaires:
      - modele/classes_utilitaires/index.md
      - Identifiant: 'references/proprietes/identifiant.md'
      - Offre: 'references/proprietes/offre.md'
      - Contribution: 'references/proprietes/contribution.md'
      - Terme: 'references/proprietes/terme.md'
      - Média: 'references/proprietes/media.md'
      - Adresse: 'references/proprietes/adresse.md'
    - Propriétés des classes: 'modele/proprietes_des_classes.md'
    - Vocabulaires contrôlés:
      - modele/vocabulaires_controles/index.md
      - Accessibilité universelle: 'references/vocabulaires/accessibilite_universelle.md'
      - Avertissements: 'references/vocabulaires/avertissements.md'
      - Disciplines artistiques: 'references/vocabulaires/disciplines_artistiques.md'
      - Public cible: 'references/vocabulaires/public_cible.md'
      - Statut d'offre: 'references/vocabulaires/statut_d_offre.md'
      - Types d'associations géographiques: 'references/vocabulaires/types_d_associations_geographiques_d_un_contributeur.md'
      - Types de configurations de salles: 'references/vocabulaires/types_de_configurations_de_salles.md'
      - Types de contenus: 'references/vocabulaires/types_de_contenus.md'
      - Types de contributeurs: 'references/vocabulaires/types_de_contributeurs.md'
      - Types de contributions: 'references/vocabulaires/types_de_contributions.md'
      - Types de lieux: 'references/vocabulaires/types_de_lieux.md'
    - Types de propriétés: 'references/types.md'
    - Exemples: 'references/exemples.md'


